all_artists_urls_path : util_files/all_urls.txt
artists_pl_path : scraped_data/artists_pl
artists_pl_backup_path : scraped_data/artists_pl_backup_20_05/artists_pl_backup
artists_non_pl_path : scraped_data/artists_not_pl
generated_data_path : generated_data/
# TODO: fix this this shouldn't be hardcoded
vocab_path : generated_data/vocab/
plots_path : plots
websty_path : generated_data/websty
korpusomat_path: scraped_data/korpusomat
korpusomat_small_path: scraped_data/korpusomat_small
corpus_path: output_data/corpus/
stopwords : util_files/stopwords.txt
Logging:
 wsd: logs/wsd.log

Genius_scraping :
  max_songs : 2000
  features : True
  save_small_artists: True
  verbose : False
  save_path: scraped_data/Genius
  GENIUS_CLIENT_ID : '803nTbhBGvR5Bv2pqnSRGr6NyLxD8YV4YhlB2rbqgd1k5SZp5Z5DPCTgCrQ7qwh7'
  GENIUS_CLIENT_SECRET : 'c5CFz-SRZbqyWFF_zOeCq88UdNeUMQdiKpzG1BGYZkd95rb8PGUZAp2xyN94sexcHKUOYVdbLtOl6TlMOdK9YA'
  GENIUS_BEARER : '6G95_WJrA_dY6h0D7JRGiE-vvvuU3L1rcltJihJQWL6TgbLokLbLUJ-4ihimBJfV'
  GENIUS_TIMEOUT : 8
  GENIUS_SLEEP_TIME : 0.03
  GENIUS_LOGFILE : logs/genius.log


LAST_FM_API_KEY : 'fe7de270a3b51d104c142236a2d0d2a7'
LAST_FM_USER_AGENT : 'Bruvhh'
SPOTIFY_USER_ID : '9cf69bb7e8f943018c43010c821d2c77'
SPOTIFY_SECRET : '4d35054ad1fa4eee866cd114a800023b'
LOGFILE_GENIUS : 'log.log'
LOGFILE_LASTFM : 'lastfm.log'

LAST_FM_FEATURES : False
wsd:
  word_limit: 5000
  outputs : generated_data/wsd_outputs_fixed
  model_name: clarin-knext/wsd-encoder
  linking_index_name: clarin-knext/wsd-linking-index
  faiss_index_path : ./ignore/encoder.faissindex
  artists:
  # - Łona_combined
  # - Bonus RPK
  # - Białas
  # - Bonson
  # - Borixon
  # - KaeN
  # - Kaz Bałagane
  - Dwa_Sławy
  # - Paluch
  # - Popek
  # # - Pezet
  # - Quebonafide
  # - Sarius
  # - Sokół_(POL)
  # - Solar
  # - Taco Hemingway
  # - VNM
  # - White 2115
  # - Young Igi
  # - Żabson

artist_names : 
- Białas
- donGURALesko
- Dudek P56
- Dwa Sławy
- Filipek
- KaeN
- Kartky
- Kaz Bałagane
- Kukon
- KęKę
- LSO
- O.S.T.R.
- PRO8L3M
- Paluch
- Peja
- Pezet
- Pikers
- Pięć Dwa
- ReTo
- Sarius
- Slums Attack
- Te-Tris
- Tede- Dudek P56
- Dwa Sławy
- Filipek
- KaeN
- Kartky
- Kaz Bałagane
- Kukon
- KęKę
- Łona_combined
- LSO
- O.S.T.R.
- PRO8L3M
- Paluch
- Peja
- Pezet
- Pikers
- Pięć Dwa
- ReTo
- Sarius
- Slums Attack
- Te-Tris
- Tede
- Ten Typ Mes
- VNM
- Vkie
- Young Igi
- Zeamsone
- Zeus (POL)
- Ten Typ Mes
- VNM
- Vkie
- Young Igi
- Zeamsone
- Zeus (POL)

top30:
- Bonus RPK
- Białas
- Bonson
- Borixon
- donGURALesko
- Dudek P56
- Filipek
- KaeN
- Kartky
- Kaz Bałagane
- Łona_combined
- O.S.T.R.
- Paluch
- Peja
- Pezet
- Pikers
- Popek
- Quebonafide
- Sarius
- Slums Attack
- Sokół_(POL)
- Solar
- Taco Hemingway
- Tede
- Ten Typ Mes
- VNM
- White 2115
- Young Igi
- Zeus (POL)
- Żabson


Small:
- ksiaze700
- Vkie
- Piekielny
- Klarenz

top10:
- Dudek P56
- Kartky
# - Łona_combined
- Slums Attack
- O.S.T.R.
- Paluch
- Peja
- donGURALesko
- White 2115
- Young Igi
- Tede