all_artists_urls_path : utils/all_urls.txt
artists_pl_path : scraped_data/artists_pl
artists_non_pl_path : scraped_data/artists_not_pl
generated_data_path : generated_data
wsd_outputs : generated_data/wsd_outputs_fixed
websty_path : generated_data/websty
stopwords : utils/stopwords.txt
Logging:
 wsd: logs/wsd.log

Genius_scraping :
  max_songs : 2000
  features : True
  save_small_artists: True
  verbose : False
  save_path: scraped_data/Genius
  GENIUS_CLIENT_ID : '803nTbhBGvR5Bv2pqnSRGr6NyLxD8YV4YhlB2rbqgd1k5SZp5Z5DPCTgCrQ7qwh7'
  GENIUS_CLIENT_SECRET : 'c5CFz-SRZbqyWFF_zOeCq88UdNeUMQdiKpzG1BGYZkd95rb8PGUZAp2xyN94sexcHKUOYVdbLtOl6TlMOdK9YA'
  GENIUS_BEARER : '6G95_WJrA_dY6h0D7JRGiE-vvvuU3L1rcltJihJQWL6TgbLokLbLUJ-4ihimBJfV'
  GENIUS_TIMEOUT : 8
  GENIUS_SLEEP_TIME : 0.03
  GENIUS_LOGFILE : logs/genius.log


LAST_FM_API_KEY : 'fe7de270a3b51d104c142236a2d0d2a7'
LAST_FM_USER_AGENT : 'Bruvhh'
SPOTIFY_USER_ID : '9cf69bb7e8f943018c43010c821d2c77'
SPOTIFY_SECRET : '4d35054ad1fa4eee866cd114a800023b'
LOGFILE_GENIUS : 'log.log'
LOGFILE_LASTFM : 'lastfm.log'

LAST_FM_FEATURES : False

artist_names : 
# - Tede
# - O.S.T.R.
# - Pikers
# - Vkie
# - Kartky
- Peja
# - Slums Attack
# - Dudek P56
# - Young Igi
# - donGURALesko
# - Filipek
# - Zeus (POL)
# - Ten Typ Mes
# # - Piekielny
- KęKę
# - Kukon
# - VNM
# - Kaz Bałagane
# - Paluch
# - PRO8L3M
# - Białas
# - Sarius
# - Zeamsone
# - Dwa Sławy
# - KaeN
# # - Klarenz
# - LSO
# - ReTo
# - Pięć Dwa
# - Te-Tris

Small:
- Vkie
- Piekielny
- Klarenz